import nodemailer from 'nodemailer';

// Helper to compile internal alert HTML template
const getInternalEmailTemplate = (inquiry, product) => {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
      <h2 style="color: #c2410c; text-align: center; border-bottom: 2px solid #c2410c; padding-bottom: 10px;">New Henco Interlock Inquiry</h2>
      <p style="font-size: 16px; color: #333;">A new inquiry has been received from the Henco Interlock website.</p>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <tr style="background-color: #f8fafc;">
          <th style="text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0;">Tracking ID</th>
          <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #c2410c;">${inquiry.trackingId}</td>
        </tr>
        <tr>
          <th style="text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0;">Client Name</th>
          <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${inquiry.name}</td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <th style="text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0;">Phone Number</th>
          <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${inquiry.phone}</td>
        </tr>
        <tr>
          <th style="text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0;">Email Address</th>
          <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${inquiry.email}</td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <th style="text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0;">Product of Interest</th>
          <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${product ? product.name : 'Unknown Product'}</td>
        </tr>
        <tr>
          <th style="text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0;">Quantity Requested</th>
          <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${inquiry.quantity} Square Feet</td>
        </tr>
        <tr style="background-color: #f8fafc;">
          <th style="text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0;">Submitted Date</th>
          <td style="padding: 10px; border-bottom: 1px solid #e2e8f0;">${new Date(inquiry.createdAt).toLocaleString()}</td>
        </tr>
      </table>
      
      <div style="margin-top: 20px; padding: 15px; background-color: #fff7ed; border-left: 4px solid #c2410c; border-radius: 4px;">
        <h4 style="margin: 0 0 10px 0; color: #c2410c;">Customer Message:</h4>
        <p style="margin: 0; font-style: italic; color: #475569;">${inquiry.message || 'No additional message provided.'}</p>
      </div>

      <p style="text-align: center; margin-top: 30px; font-size: 12px; color: #64748b;">
        This email was automatically generated by the Henco Interlock Website Portal.
      </p>
    </div>
  `;
};

// Helper to compile client receipt HTML template
const getClientEmailTemplate = (inquiry, product) => {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
      <div style="text-align: center; margin-bottom: 20px;">
        <h1 style="color: #c2410c; margin: 0;">Henco Interlock</h1>
        <p style="color: #64748b; margin: 5px 0 0 0; font-size: 14px;">Premium Paving & Landscaping Solutions</p>
      </div>
      
      <h3 style="color: #334155;">Hello ${inquiry.name},</h3>
      <p style="color: #334155; line-height: 1.6;">
        Thank you for reaching out to Henco Interlock. We have successfully received your inquiry regarding our <strong>${product ? product.name : 'premium landscaping products'}</strong>.
      </p>

      <p style="color: #334155; line-height: 1.6;">
        Our sales team is currently reviewing your parameters and will get in touch with you shortly at <strong>${inquiry.phone}</strong> or by replying directly to this email address.
      </p>

      <div style="margin: 25px 0; padding: 20px; background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; text-align: center;">
        <span style="color: #64748b; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; display: block;">Your Inquiry Tracking ID</span>
        <strong style="color: #c2410c; font-size: 24px; display: block; margin-top: 8px; font-family: monospace;">${inquiry.trackingId}</strong>
        <p style="margin: 8px 0 0 0; font-size: 12px; color: #94a3b8;">
          Use this tracking ID on our website to review the real-time status of your request.
        </p>
      </div>

      <h4 style="color: #334155; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; margin-top: 30px;">Summary of Parameters:</h4>
      <ul style="color: #475569; padding-left: 20px; line-height: 1.8;">
        <li><strong>Product:</strong> ${product ? product.name : 'Custom Selection'}</li>
        <li><strong>Est. Volume:</strong> ${inquiry.quantity} Sq. Ft.</li>
        <li><strong>Current Status:</strong> Pending Review</li>
      </ul>

      <p style="color: #334155; font-size: 14px; margin-top: 30px; line-height: 1.6;">
        Warm regards,<br />
        <strong>The Sales Team</strong><br />
        Henco Interlock Industries
      </p>
      
      <div style="margin-top: 40px; padding-top: 15px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 11px; color: #94a3b8;">
        &copy; ${new Date().getFullYear()} Henco Interlock. All rights reserved.
      </div>
    </div>
  `;
};

export const sendInquiryEmails = async (inquiry, product) => {
  const host = process.env.EMAIL_HOST;
  const port = process.env.EMAIL_PORT;
  const user = process.env.EMAIL_USER;
  const pass = process.env.EMAIL_PASS;
  const companyEmail = process.env.COMPANY_EMAIL || 'sales@hencointerlock.com';

  const isMock = !user || !pass || user === 'your-email@gmail.com' || pass === 'your-gmail-app-password';

  if (isMock) {
    console.log('\n=================== [MOCK EMAIL LOG] ===================');
    console.log(`[Status]: SMTP Credentials are not configured. Logging details.`);
    console.log(`[To Internal Office (${companyEmail})]:`);
    console.log(`- Subject: 🚨 NEW WEBSITE INQUIRY [${inquiry.trackingId}]`);
    console.log(`- Product: ${product ? product.name : 'Unknown'}`);
    console.log(`- Quantity: ${inquiry.quantity} Sq. Ft.`);
    console.log(`- Client: ${inquiry.name} (${inquiry.email} | ${inquiry.phone})`);
    console.log(`- Message: ${inquiry.message || 'None'}`);
    console.log(`--------------------------------------------------------`);
    console.log(`[To Client (${inquiry.email})]:`);
    console.log(`- Subject: Inquiry Received - Tracking ID: ${inquiry.trackingId}`);
    console.log(`- Tracking: Please visit the inquiry lookup with ID ${inquiry.trackingId}`);
    console.log('========================================================\n');
    return true;
  }

  try {
    const transporter = nodemailer.createTransport({
      host: host,
      port: Number(port) || 587,
      secure: Number(port) === 465, // True for port 465, false for others
      auth: {
        user: user,
        pass: pass,
      },
    });

    // 1. Send Internal Alert
    const internalMailOptions = {
      from: `"Henco Website" <${user}>`,
      to: companyEmail,
      subject: `🚨 NEW WEBSITE INQUIRY [${inquiry.trackingId}] - ${inquiry.name}`,
      html: getInternalEmailTemplate(inquiry, product),
    };
    await transporter.sendMail(internalMailOptions);

    // 2. Send Client Receipt
    const clientMailOptions = {
      from: `"Henco Interlock" <${companyEmail}>`,
      to: inquiry.email,
      subject: `Inquiry Received - Tracking ID: ${inquiry.trackingId}`,
      html: getClientEmailTemplate(inquiry, product),
    };
    await transporter.sendMail(clientMailOptions);

    console.log(`✔ Inquiry emails dispatched successfully for tracking ID ${inquiry.trackingId}`);
    return true;
  } catch (error) {
    console.error(`❌ Failed to send inquiry emails via SMTP:`, error.message);
    // Graceful failure: log output locally, and don't crash backend
    return false;
  }
};
